logging:
  level:
    com.example.dashboard: debug
#    org.springframework: trace

meters:
  system: macosx
  cpu:
    command: "ps -A -o %cpu | awk '{s+=$1} END {print s \"%\"}'"
  mem:
    command: "top -l 1 | grep PhysMem: | awk '{print $2}'"
  swap:
    command: "sysctl vm.swapusage"
  disk:
    command: "df -h | grep /$ | awk '{print $5}'"